#!/bin/bash

echo "🚀 RoamWise Deployment Commands"
echo "==============================="
echo ""
echo "Run these commands one by one:"
echo ""
echo "# 1. Navigate to the project folder"
echo "cd /Users/galsened/Downloads/RoamWise-frontend-WX"
echo ""
echo "# 2. Authenticate GitHub CLI (just follow the prompts)"
echo "gh auth login"
echo ""
echo "# 3. Create the repository"
echo "gh repo create roamwise-app --public --description 'RoamWise - Travel & Local Discovery PWA'"
echo ""
echo "# 4. Add remote and push"
echo "git remote add origin https://github.com/galsened/roamwise-app.git"
echo "git push -u origin main"
echo ""
echo "# 5. Enable GitHub Pages"
echo 'gh api repos/galsened/roamwise-app --method PATCH --field "pages[source][branch]=main" --field "pages[source][path]=/"'
echo ""
echo "🎉 Your app will be live at: https://galsened.github.io/roamwise-app/"